
name: 收集整理待测网址
# 分支 应替换为  branches
on:
  schedule:
    - cron: '28 22 * * *'
  workflow_dispatch:
    branches:
      - main

permissions:
  contents: write
  
jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: GetTime
      id: date
      run: echo "::set-output name=date::$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install requests
      run: pip install requests

    - name: Run blacklist update
      run: python ${{ github.workspace }}/Collect_organize.py

    - name: 更新 EPG.xml 和 README.md
      run: |
        rm -f EPG.xml && wget https://epg.112114.xyz/pp.xml -O EPG.xml
        echo "待检测文件 test.txt test.m3u 已于 ${{ steps.date.outputs.date }} 生成，本仓库访客数：![Visitor's Count](https://profile-counter.glitch.me/pxiptv_TV/count.svg)" > README.md      
    
    - name: Commit changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git commit -am "${{ steps.date.outputs.date }}"
        if [ -n "$(git status --porcelain)" ]; then
        git add test.txt test.m3u online.txt EPG.xml README.md
        #  iptv.txt iptv.m3u blacklist.txt whitelist.txt online.txt tv.txt live.txt others.txt test.txt test.m3u EPG.xml README.md
        git commit -m "Automatic update"
        git push
        else
          echo "No changes detected, skipping commit."
        fi
        
env:
  TZ: Asia/Shanghai
