
name: 手动更新频道网址
# 分支 应替换为  branches
on:
  workflow_dispatch:
    branches:
      - main

permissions:
  contents: write
  
jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: GetTime
      id: date
      run: echo "::set-output name=date::$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Run blacklist update
      run: python ${{ github.workspace }}/Collect_filtering.py

    - name: 更新 EPG.xml 和 README.md
      run: |
        rm -f EPG.xml && wget https://epg.112114.xyz/pp.xml -O EPG.xml
        echo "待检测文件 test.txt test.m3u 已于 ${{ steps.date.outputs.date }} 生成，本仓库访客数：![Visitor's Count](https://profile-counter.glitch.me/pxiptv_TV/count.svg)" > README.md      
    
    - name: Commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -am "${{ steps.date.outputs.date }}"
        if [ -n "$(git status --porcelain)" ]; then
        git add iptv.txt iptv.m3u blacklist.txt EPG.xml README.md
          iptv.txt iptv.m3u blacklist.txt whitelist.txt online.txt tv.txt live.txt others.txt test.txt test.m3u EPG.xml README.md
        git commit -m ":tada:  AutoUpdate $(date +'%Y%m%d')"
        git push
        else
          echo "No changes detected, skipping commit."
        fi

        current_datetime=$(date +"%Y%m%d_%H%M%S")
        cp iptv.m3u history/"${current_datetime}_IPTV.m3u"
        cp iptv.txt history/"${current_datetime}_IPTV.txt"
        git add history/"${current_datetime}_IPTV.m3u"
        git add history/"${current_datetime}_IPTV.txt"
        git commit -m "Archive file with timestamp"
        git push

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      
env:
  TZ: Asia/Shanghai
