name: 频道地址更新

on:
  workflow_dispatch:
  watch:
    types: [started]
  schedule:
    - cron: '0 1 * * *'

permissions:
  contents: write
  
jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: GetTime
      run: echo "DATE=$(date +'%Y-%m-%d %H:%M:%S CST')" >> $GITHUB_ENV

    - name: Update
      run: |
        # 央视源
        rm -f CCTV.m3u && wget https://raw.githubusercontent.com/YueChan/Live/main/IPTV.m3u -O CCTV.m3u
        sed -i -n '/CCTV-1\|CCTV-2\|CCTV-3\|CCTV-4\|CCTV-5\|CCTV-5\|CCTV-6\|CCTV-7\|CCTV-8\|CCTV-9\|CCTV-10\|CCTV-11\|CCTV-12\|CCTV-13\|CCTV-14\|CCTV-15\|CCTV-16\|CCTV-17\|CCTV-4K\|CCTV-8K\+/,+1p' CCTV.m3u
        sed -i 's/央视频道/央视/' CCTV.m3u
        sed -i '/联通/,+1d' CCTV.m3u
        sed -i '1i #EXTM3U' CCTV.m3u
        sed -i '/^\s*$/d' CCTV.m3u
        
        # 频道
        rm -f IPTV.m3u && wget https://raw.githubusercontent.com/YueChan/Live/main/IPTV.m3u -O IPTV.m3u
        rm -f IPTV.txt && wget https://raw.githubusercontent.com/Fairy8o/IPTV/main/DIYP-v4.txt -O IPTV.txt
        
        # 节目源
        rm -f EPG.xml && wget https://epg.112114.xyz/pp.xml -O EPG.xml
        echo "已于 $DATE 自动更新频道" > README.md
              
    - name: Commit and push if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        if [[ -f "IPTV.m3u" ]]; then
          git add IPTV.m3u
        fi
        if [[ -f "IPTV.txt" ]]; then
          git add IPTV.txt
        fi
        if [[ -f "EPG.xml" ]]; then
          git add EPG.xml
        fi
        if ! git diff --staged --quiet; then
          git commit -m "Auto-update IPTV.m3u"
          git push
        fi
        
        current_datetime=$(date +"%Y%m%d_%H%M%S")
        cp IPTV.m3u history/"${current_datetime}_IPTV.m3u"
        cp IPTV.txt history/"${current_datetime}_IPTV.txt"
        git add history/"${current_datetime}_IPTV.m3u"
        git add history/"${current_datetime}_IPTV.txt"
        git commit -m "Archive file with timestamp"

env:
  TZ: Asia/Shanghai
