
name: 电视节目网址更新
# 分支 应替换为  branches
on:
  schedule:
    - cron: '08 22 * * *'
  workflow_dispatch:
    branches:
      - main

permissions:
  contents: write
  
jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: GetTime
      id: date
      run: echo "::set-output name=date::$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run IPTV update
      run: python ${{ github.workspace }}/iptv.py
   
    - name: Run blacklist update
      run: python ${{ github.workspace }}/blacklist.py
    
    - name: Upload generated files
      uses: actions/upload-artifact@v2
      with:
        name: generated-files
        path: |
          iptv.txt
          others.txt
          
    - name: 更新 EPG.xml 和 README.md
      run: |
        rm -f EPG.xml && wget https://epg.112114.xyz/pp.xml -O EPG.xml
        echo "iptv.m3u 的网址 已于 ${{ steps.date.outputs.date }} 更新，本仓库访客数：![Visitor's Count](https://profile-counter.glitch.me/pxiptv_TV/count.svg)" > README.md      
    
    - name: Commit changes
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -am "${{ steps.date.outputs.date }}"
          if [[ -f "iptv.m3u" ]]; then
          git add iptv.m3u
          fi
          if [[ -f "iptv.txt" ]]; then
          git add iptv.txt
          fi
          if [[ -f "other.txt" ]]; then
          git add other.txt
          fi
          if [[ -f "blacklist_auto.txt" ]]; then
          git add blacklist_auto.txt
          fi
          if [[ -f "whitelist_auto.txt" ]]; then
          git add whitelist_auto.txt
          fi
          git commit -m ":tada:  AutoUpdate $(date +'%Y%m%d')"
          git add README.md
        
          current_datetime=$(date +"%Y%m%d_%H%M%S")
          cp iptv.m3u history/"${current_datetime}_IPTV.m3u"
          cp iptv.txt history/"${current_datetime}_IPTV.txt"
          git add history/"${current_datetime}_IPTV.m3u"
          git add history/"${current_datetime}_IPTV.txt"
          git commit -m "Archive file with timestamp"
          git push
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
env:
  TZ: Asia/Shanghai
