
name: 文件去重
# 分支 应替换为  branches
on:
  schedule:
    - cron: '08 22 * * *'
  workflow_dispatch:
    branches:
      - main

permissions:
  contents: write
  
jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: GetTime
      id: date
      run: echo "::set-output name=date::$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run IPTV update
      run: python ${{ github.workspace }}/iptv.py
   
    - name: Run blacklist update
      run: python ${{ github.workspace }}/blacklist.py
    
    - name: Upload generated files
      uses: actions/upload-artifact@v2
      with:
        name: generated-files
        path: |
          iptv.txt
          others.txt
          
    - name: Commit changes
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add iptv.txt
          git add iptv.m3u
          git add others.txt
          git add blacklist_auto.txt
          git add whitelist_auto.txt
          git commit -m ":tada:  AutoUpdate $(date +'%Y%m%d')"

        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
env:
  TZ: Asia/Shanghai
