name: 电视节目地址分类更新  
# 分支 应替换为  branches
on:
  schedule:
    - cron: '08 22 * * *'
  workflow_dispatch:
    branches:
      - main

permissions:
  contents: write
  
jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: GetTime
      id: date
      run: echo "::set-output name=date::$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run IPTV update
      run: python ${{ github.workspace }}/iptv.py

    # 节目源
    - name: 更新 EPG.xml 和 README.md
      run: |
        rm -f EPG.xml && wget https://epg.112114.xyz/pp.xml -O EPG.xml
        echo "iptv.m3u 的网址 已于 ${{ steps.date.outputs.date }} 更新，本仓库访客数：![Visitor's Count](https://profile-counter.glitch.me/pxiptv_TV/count.svg)" > README.md
        
    - name: Commit results
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -am "${{ steps.date.outputs.date }}"
        if [ -n "$(git status --porcelain)" ]; then
        git add *.txt
        git commit -m "Automatic update"
        git push
        else
          echo "No changes detected, skipping commit."
        fi
        git add README.md
        
        current_datetime=$(date +"%Y%m%d_%H%M%S")
        cp iptv.m3u history/"${current_datetime}_LIVE.m3u"
        cp iptv.txt history/"${current_datetime}_LIVE.txt"
        git add history/"${current_datetime}_LIVE.m3u"
        git add history/"${current_datetime}_LIVE.txt"
        git commit -m "Archive file with timestamp"
        git push
        
env:
  TZ: Asia/Shanghai
